from fastapi import APIRouter

from app.verification.evidence import EvidenceRecord
from app.verification.store import evidence_store
from app.verification.verifier import Verifier


router = APIRouter(
    prefix="/verification",
    tags=["Verification"],
)


verifier = Verifier()


@router.post("/check")
def verify_state(
    expected: str,
    actual: str,
    evidence: str,
):
    """
    Verify an observed state against an expected state.
    """

    evidence_record = EvidenceRecord(
        source="api",
        claim=f"Expected state is {expected}",
        value=evidence,
        verdict="AVAILABLE",
        evidence_type="STATE_CHECK",
    )

    verdict = verifier.verify(
        expected=expected,
        actual=actual,
        evidence=evidence_record,
    )

    # Store the completed evidence record.
    evidence_store.add(
        source=evidence_record.source,
        claim=evidence_record.claim,
        value=evidence_record.value,
        verdict=verdict.value,
        evidence_type=evidence_record.evidence_type,
        metadata=evidence_record.metadata,
    )

    return {
        "expected": expected,
        "actual": actual,
        "verdict": verdict.value,
        "evidence": evidence_store.get_all()[-1],
    }


@router.get("/evidence")
def get_evidence():
    """
    Return all evidence generated by the running backend.
    """

    return {
        "count": evidence_store.count(),
        "evidence": evidence_store.get_all(),
    }


@router.delete("/evidence")
def clear_evidence():
    """
    Clear temporary in-memory evidence.

    Useful during development and testing.
    """

    evidence_store.clear()

    return {
        "status": "CLEARED",
        "count": evidence_store.count(),
    }